### ISSUE TITLE
Mod version incorrect in Release

### ISSUE THREAD

**Issue by DubyaDude** [Rafacasari/Playerspace-Mover#1]
![dnSpy_Enc6yu3x4a](https://user-images.githubusercontent.com/13679909/103468056-66debe80-4d23-11eb-8749-cd532b8a5d93.png)

This is the DLL from https://github.com/Rafacasari/Playerspace-Mover/releases/tag/1.1.0
Version is incorrect compared to release version

**Comment by Rafacasari** [comment]
✔
