### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by avail** [Rafacasari/Playerspace-Mover#3]
since you're maintaining the version that's published in the modding discord, you can use [my code](https://github.com/nekoclient/NekoClient-ML/commit/3e92cd7e712fe0b27bffdaaf6b3e9931514e9d2f) if you want to update it.

edit: technically with this change it should work for any game using Oculus.VR.dll, not just vrchat

**Comment by Rafacasari** [comment]
Thank you ❤
